from typing import Dict, Any, List

def format_final_report(
    ocr_text: str,
    tagged_values: Dict[str, Dict[str, Any]],
    llama_analysis: str,
    meditron_analysis: str,
    biomistral_analysis: str,
    extraction_method: str = "regex"
) -> Dict[str, Any]:
    """
    Assembles the outputs of all pipeline steps into a single, well-structured dictionary.
    
    Args:
        ocr_text: Cleaned OCR text from the report.
        tagged_values: Dictionary of annotated lab results.
        llama_analysis: Preliminary analysis from LLaMA.
        meditron_analysis: Audited analysis from Meditron.
        biomistral_analysis: Patient-friendly explanation from BioMistral.
        extraction_method: How values were extracted ("regex", "llm-fallback", "hybrid").
    """
    # Separate normal and abnormal values for clean UI display
    normal_values = []
    abnormal_values = []
    
    for key, item in tagged_values.items():
        val_entry = {
            "parameter": item["name"],
            "value": item["value"],
            "unit": item["unit"],
            "ref_range": item["ref"],
            "status": item["status"]
        }
        if item["status"] in ["HIGH", "LOW"]:
            abnormal_values.append(val_entry)
        else:
            normal_values.append(val_entry)
            
    # Risk flags (simple listing of abnormal values)
    risk_flags = [
        f"{val['parameter']} is {val['status']} ({val['value']} {val['unit']}, Ref: {val['ref_range']})"
        for val in abnormal_values
    ]

    return {
        "metadata": {
            "total_extracted_parameters": len(tagged_values),
            "abnormal_count": len(abnormal_values),
            "normal_count": len(normal_values),
            "extraction_method": extraction_method
        },
        "abnormal_values": abnormal_values,
        "normal_values": normal_values,
        "risk_flags": risk_flags,
        "clinical_analysis": {
            "preliminary": llama_analysis,
            "audited": meditron_analysis
        },
        "patient_explanation": biomistral_analysis,
        "raw_ocr_text": ocr_text,
        "disclaimer": (
            "DISCLAIMER: This analysis report is generated by an artificial intelligence system "
            "for educational and informational assistance only. It does NOT constitute a final "
            "medical diagnosis or professional medical advice. Always consult a qualified medical "
            "practitioner or physician to interpret your laboratory test results and formulate "
            "a treatment plan."
        )
    }
