from app.config import BIOMISTRAL_MODEL_PATH, GPU_LAYERS_DEFAULT, CONTEXT_WINDOW_DEFAULT, MAX_TOKENS_DEFAULT
from modules.llm.model_runner import run_gguf_inference
from modules.llm.prompt_templates import BIOMISTRAL_SYSTEM_PROMPT, BIOMISTRAL_USER_TEMPLATE

def run_biomistral_refinement(
    meditron_analysis: str,
    gpu_layers: int = GPU_LAYERS_DEFAULT
) -> str:
    """
    Polishes clinical report into patient-friendly simplified language using BioMistral 7B.
    
    Includes a guard against empty/too-short input from previous pipeline stages.
    """
    # Guard: if meditron_analysis is empty or too short, provide structured fallback
    if not meditron_analysis or len(meditron_analysis.strip()) < 50:
        meditron_analysis = (
            "The medical report analysis is currently limited. "
            "Please provide a comprehensive patient-friendly explanation covering: "
            "1) What blood tests were performed, "
            "2) General guidance on understanding lab results, "
            "3) The importance of consulting a doctor for proper interpretation, "
            "4) Common questions patients should ask their physician about lab results."
        )
    
    user_prompt = BIOMISTRAL_USER_TEMPLATE.format(meditron_analysis=meditron_analysis)
    
    result = run_gguf_inference(
        model_path=str(BIOMISTRAL_MODEL_PATH),
        system_prompt=BIOMISTRAL_SYSTEM_PROMPT,
        user_prompt=user_prompt,
        n_gpu_layers=gpu_layers,
        n_ctx=CONTEXT_WINDOW_DEFAULT,
        max_tokens=MAX_TOKENS_DEFAULT,
        temperature=0.3  # Some temperature allowed for conversational readability
    )
    
    # Post-inference guard: if output is still too short, append fallback
    if len(result.strip()) < 100:
        result += (
            "\n\n## Important Disclaimer\n"
            "This analysis is generated by an AI system for educational purposes only. "
            "It does NOT constitute medical advice, diagnosis, or treatment. "
            "Please consult your doctor or healthcare provider to properly interpret "
            "your lab results and discuss any health concerns."
        )
    
    return result
